import {useEffect,useMemo,useState} from "react";
import {demoCatalog} from "./services/catalog/mock";
import {loadSupabaseCatalog} from "./services/catalog/supabase";
import {filterCatalog} from "./domain/catalog";
import {demoNotifications} from "./data/notifications";
const nav=["Home","Apps","Updates","Downloads","Settings"];
export default function App(){
 const[tab,setTab]=useState("Home"),[dark,setDark]=useState(true),[q,setQ]=useState(""),[showNotifications,setShowNotifications]=useState(false),[apps,setApps]=useState(demoCatalog),[connected,setConnected]=useState(false);
 useEffect(()=>{loadSupabaseCatalog().then(x=>{setApps(x);setConnected(true)}).catch(()=>setConnected(false))},[]);
 const filtered=useMemo(()=>filterCatalog(apps,{query:q}),[apps,q]),unread=demoNotifications.filter(n=>!n.read).length;
 return <main className={dark?"store dark":"store"}><header><div className="brand"><span>A</span>EM <small>STORE</small></div><div className="head-actions"><button onClick={()=>setDark(!dark)}>{dark?"Light":"Dark"}</button><button className="icon" title="Notifications" onClick={()=>setShowNotifications(!showNotifications)}>♢ {unread}</button></div></header>
 {showNotifications&&<section className="notification-panel"><b>Notifications</b>{demoNotifications.map(n=><p key={n.id}><strong>{n.title}</strong><br/>{n.body}</p>)}</section>}
 <nav>{nav.map(n=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}>{n}</button>)}</nav>
 {tab==="Home"&&<section className="hero"><p className="eyebrow">AEM STORE</p><h1>Your software.<br/><em>One place.</em></h1><p>Discover, install and update applications from your own projects without replacing the build systems that created them.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search apps, tools and releases"/></div></section>}
 {tab==="Apps"||tab==="Home"?<section className="content"><div className="section-head"><div><span>LIBRARY</span><h2>{tab==="Home"?"Your applications":"All applications"}</h2></div><span>{filtered.length} apps · {connected?"LIVE":"DEMO"}</span></div><div className="grid">{filtered.map(a=><article className="card" key={a.id.project}><div className="app-icon">{a.name[0]}</div><div className="card-main"><div className="meta">{a.category} · {a.platforms.join(" · ")}</div><h3>{a.name}</h3><p>{a.description}</p><div className="chips">{a.functionality.slice(0,3).map(x=><span key={x}>{x}</span>)}</div></div><button className="install" onClick={()=>window.open(a.sourceUrl?`${a.sourceUrl}/releases/latest`:"#","_blank")}>INSTALL</button><details><summary>Details</summary><p><b>Source</b> · GitHub · {a.id.project}</p><p><b>Permissions</b> · {a.permissions.join(", ")||"None listed"}</p></details></article>)}</div></section>:<section className="empty"><h2>{tab}</h2><p>{tab==="Updates"?"AEM will show available releases and version changes here.":tab==="Downloads"?"Downloaded releases and installation history will appear here.":"Store preferences, language, notifications and installer settings will appear here."}</p></section>}
 <footer><span>● {connected?"Supabase connected":"Using local catalog"}</span><span>Android · Windows · Linux · macOS · Web</span></footer></main>
}