import {useEffect,useMemo,useState} from "react";
import {Capacitor,registerPlugin} from "@capacitor/core";
import {loadSupabaseCatalog} from "./services/catalog/supabase";
import {filterCatalog} from "./domain/catalog";
import {requestGithubBuild,listBuildRequests} from "./services/builds/github";
import {listNotifications,markNotificationRead} from "./services/notifications/contract";
import {listDownloads,recordDownload,updateDownload} from "./services/downloads/manager";
import {listReleaseHistory} from "./services/releases/history";
import {getSourceSyncState,listSourceProviders} from "./services/providers/catalog";

type InstallerMode="system"|"split";
type InstallerBridge={downloadAndInstall:(o:{url:string;filename?:string;mode?:InstallerMode;sha256?:string;packageIdentity?:string;downloadId?:string;wifiOnly?:boolean})=>Promise<{permissionRequired?:boolean;started?:boolean}>;cancelDownload:(o:{downloadId:string})=>Promise<{cancelled?:boolean}>;addListener:(eventName:string,listener:(data:any)=>void)=>Promise<{remove:()=>Promise<void>}>;openInstallPermission:()=>Promise<void>;getInstalledVersions:(o?:{packages?:string[]})=>Promise<{apps:Array<{packageName:string;versionName:string;versionCode:number}>}>;openInstalled:(o:{packageName:string})=>Promise<{started?:boolean}>};
const AemInstaller=registerPlugin<InstallerBridge>("AemInstaller");
const nav=["Home","Apps","Build","Updates","Downloads","Admin","Settings"];

export default function App(){
 const[tab,setTab]=useState("Home"),[dark,setDark]=useState(true),[q,setQ]=useState(""),[showNotifications,setShowNotifications]=useState(false);
 const[apps,setApps]=useState<any[]>([]),[connected,setConnected]=useState(false),[builds,setBuilds]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[downloads,setDownloads]=useState<any[]>([]),[syncState,setSyncState]=useState<any>(null),[providers,setProviders]=useState<any[]>([]);
 const[repo,setRepo]=useState(""),[ref,setRef]=useState("main"),[variant,setVariant]=useState("debug"),[channel,setChannel]=useState<"stable"|"beta"|"development">("development"),[building,setBuilding]=useState(false),[buildMessage,setBuildMessage]=useState("");
 const[githubSearch,setGithubSearch]=useState(""),[githubResults,setGithubResults]=useState<any[]>([]),[searchingGithub,setSearchingGithub]=useState(false),[selected,setSelected]=useState<any|null>(null),[releaseHistory,setReleaseHistory]=useState<any[]>([]);
 const[installed,setInstalled]=useState<Record<string,{versionName:string;versionCode:number}>>({}),[downloadProgress,setDownloadProgress]=useState<Record<string,{bytes:number;total:number}>>({}),[appearance,setAppearance]=useState<"light"|"dark"|"system">("dark"),[installer,setInstaller]=useState<InstallerMode>("split"),[settingsOpen,setSettingsOpen]=useState<string|null>(null),[catalogChannel,setCatalogChannel]=useState<"stable"|"beta"|"development">("stable"),[notificationsEnabled,setNotificationsEnabled]=useState(true),[autoSync,setAutoSync]=useState(true),[wifiOnly,setWifiOnly]=useState(false),[downloadUnit,setDownloadUnit]=useState<"auto"|"B"|"KB"|"MB"|"GB">("auto"),[syncing,setSyncing]=useState(false);
 const load=async()=>{setSyncing(true);try{const x=await loadSupabaseCatalog();setApps(x);setConnected(true);if(Capacitor.isNativePlatform()){const packages=x.map((a:any)=>a.packageIdentity||a.latest?.stable?.artifacts?.find((z:any)=>z.packageIdentity)?.packageIdentity).filter(Boolean);AemInstaller.getInstalledVersions({packages}).then(r=>setInstalled(Object.fromEntries(r.apps.map(v=>[v.packageName,{versionName:v.versionName,versionCode:v.versionCode}])))).catch(()=>{})}}catch(e){setConnected(false)}try{setSyncState(await getSourceSyncState("github"))}catch{}try{setProviders(await listSourceProviders())}catch{}listBuildRequests().then(setBuilds).catch(()=>{});listNotifications().then(setNotifications).catch(()=>{});listDownloads().then(setDownloads).catch(()=>{});setSyncing(false)};
 useEffect(()=>{load();const refresh=()=>{if(autoSync)load()};window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);const t=setInterval(()=>{if(autoSync)load()},300000);return()=>{clearInterval(t);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh)}},[autoSync]);

 useEffect(()=>{if(!Capacitor.isNativePlatform())return;let handle:any;AemInstaller.addListener("downloadProgress",(p:any)=>{if(!p?.downloadId)return;setDownloadProgress(v=>({...v,[p.downloadId]:{bytes:Number(p.bytesDownloaded||0),total:Number(p.totalBytes||0)}}));updateDownload(String(p.downloadId),{bytesDownloaded:Number(p.bytesDownloaded||0),totalBytes:Number(p.totalBytes||0)}).catch(()=>{})}).then(h=>{handle=h}).catch(()=>{});return()=>{handle?.remove?.()}},[]);
 useEffect(()=>{const saved=localStorage.getItem("aem-installer") as InstallerMode|null;if(saved)setInstaller(saved);const a=localStorage.getItem("aem-appearance") as any;if(a)setAppearance(a);const ch=localStorage.getItem("aem-channel") as any;if(ch)setCatalogChannel(ch);setNotificationsEnabled(localStorage.getItem("aem-notifications")!=="off");setAutoSync(localStorage.getItem("aem-auto-sync")!=="off");setWifiOnly(localStorage.getItem("aem-wifi-only")==="on");const du=localStorage.getItem("aem-download-unit") as any;if(["auto","B","KB","MB","GB"].includes(du))setDownloadUnit(du)},[]);
 useEffect(()=>{const isDark=appearance==="dark"||(appearance==="system"&&window.matchMedia?.("(prefers-color-scheme: dark)").matches);setDark(isDark)},[appearance]);
 const filtered=useMemo(()=>filterCatalog(apps,{query:q}),[apps,q]),unread=notifications.filter(n=>!n.read).length;
 async function searchGithub(){if(!githubSearch.trim())return;setSearchingGithub(true);try{const r=await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(githubSearch+" android")}&per_page=10`);const j=await r.json();setGithubResults(j.items||[])}finally{setSearchingGithub(false)}}
 function addGithub(name:string){setRepo(name);setTab("Build");setBuildMessage("Repository selected. Choose the build options and press BUILD APK.")}
 async function build(){setBuildMessage("");setBuilding(true);try{await requestGithubBuild({repository:repo,ref,variant,channel});setRepo("");setBuildMessage("Queued. AEM will build and publish it automatically.");load()}catch(e){setBuildMessage(e instanceof Error?e.message:"Build request failed")}finally{setBuilding(false)}}
 async function install(app:any){const release=app.latest?.[catalogChannel]||app.latest?.stable||app.latest?.beta||app.latest?.development;const artifact=release?.artifacts?.find((x:any)=>["apk","apks","xapk","apkm"].includes(x.kind));if(!artifact){setBuildMessage(`No APK package is published yet for ${app.name}. AEM will keep checking the repository for one.`);setTab("Build");setRepo(app.id.project);return}if(!Capacitor.isNativePlatform()){window.open(artifact.downloadUrl,"_blank");return}let downloadId:string|undefined;try{const row=await recordDownload({appId:String(app.databaseId),releaseId:String(release.id),filename:artifact.filename,url:artifact.downloadUrl,status:"downloading",bytesDownloaded:0,totalBytes:artifact.sizeBytes});downloadId=String(row.id);const result=await AemInstaller.downloadAndInstall({url:artifact.downloadUrl,filename:artifact.filename,mode:installer,sha256:artifact.sha256,packageIdentity:artifact.packageIdentity||app.packageIdentity,downloadId,wifiOnly});if(result.permissionRequired){if(downloadId)await updateDownload(downloadId,{status:"cancelled",error:"Android installation permission required"});await AemInstaller.openInstallPermission();return}if(downloadId)await updateDownload(downloadId,{status:"completed",bytesDownloaded:artifact.sizeBytes||0,totalBytes:artifact.sizeBytes});setTimeout(load,1500);setTimeout(load,5000)}catch(e){if(downloadId){const message=e instanceof Error?e.message:"Installation failed";await updateDownload(downloadId,{status:message.toLowerCase().includes("cancel")?"cancelled":"failed",error:message}).catch(()=>{});}setBuildMessage(e instanceof Error?e.message:"Installation failed");}}
 async function installRelease(app:any,release:any){const artifact=release?.artifacts?.find((x:any)=>["apk","apks","xapk","apkm"].includes(x.kind));if(!artifact){setBuildMessage("That release has no installable Android package.");return;}await install({...app,latest:{[catalogChannel]:release},packageIdentity:app.packageIdentity||artifact.packageIdentity})}
 function openApp(app:any){setSelected(app);setReleaseHistory([]);setTab("App");if(app.databaseId)listReleaseHistory(app.databaseId).then(setReleaseHistory).catch(()=>{})}
 function saveAppearance(v:any){setAppearance(v);localStorage.setItem("aem-appearance",v)}
 function saveInstaller(v:InstallerMode){setInstaller(v);localStorage.setItem("aem-installer",v)}
 function saveChannel(v:any){setCatalogChannel(v);localStorage.setItem("aem-channel",v)}
 function saveToggle(key:string,setter:(v:boolean)=>void,v:boolean){setter(v);localStorage.setItem(key,v?"on":"off")} function saveDownloadUnit(v:any){setDownloadUnit(v);localStorage.setItem("aem-download-unit",v)}
 return <main className={dark?"store dark":"store"}>
  <header><div className="brand"><span>A</span>EM <small>STORE</small></div><div className="head-actions"><button onClick={()=>saveAppearance(dark?"light":"dark")}>{dark?"Light":"Dark"}</button><button className="icon" onClick={()=>setShowNotifications(!showNotifications)}>♢ {unread}</button></div></header>
  {showNotifications&&<section className="notification-panel"><b>Notifications</b>{notifications.length?notifications.map(n=><p key={n.id} onClick={()=>markNotificationRead(n.id).then(load)}><strong>{n.title}</strong><br/>{n.body}</p>):<p>No notifications yet.</p>}</section>}
  <nav>{nav.map(n=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}>{n}</button>)}</nav>

  {tab==="Home"&&<><section className="hero"><p className="eyebrow">AEM STORE</p><h1>Your software.<br/><em>One place.</em></h1><p>Discover, build, install and update applications from your repositories and published APKs.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search apps, tools and releases"/></div></section><section className="content"><div className="section-head"><div><span>LIBRARY</span><h2>Your applications</h2></div><span>{filtered.length} apps · {connected?"LIVE":"DEMO"}</span></div><div className="grid">{filtered.map(a=><AppCard key={a.id.project} app={a} onOpen={()=>openApp(a)} onInstall={()=>install(a)} onOpenInstalled={(p)=>Capacitor.isNativePlatform()?AemInstaller.openInstalled({packageName:p}):window.open(a.sourceUrl,"_blank")} installed={(() => { const p=a.packageIdentity||a.latest?.stable?.artifacts?.find((x:any)=>x.packageIdentity)?.packageIdentity; return p?installed[p]:undefined; })()}/>)}</div></section></>}

  {tab==="Apps"&&<section className="content"><div className="section-head"><div><span>LIBRARY</span><h2>All applications</h2></div><span>{filtered.length} apps</span></div><div className="grid">{filtered.map(a=><AppCard key={a.id.project} app={a} onOpen={()=>openApp(a)} onInstall={()=>install(a)} onOpenInstalled={(p)=>Capacitor.isNativePlatform()?AemInstaller.openInstalled({packageName:p}):window.open(a.sourceUrl,"_blank")} installed={(() => { const p=a.packageIdentity||a.latest?.stable?.artifacts?.find((x:any)=>x.packageIdentity)?.packageIdentity; return p?installed[p]:undefined; })()}/>)}</div></section>}

  {tab==="App"&&selected&&<section className="content app-page"><button onClick={()=>setTab("Apps")}>← Back to Apps</button><div className="app-detail"><div className="app-icon large">{selected.name[0]}</div><div><span className="meta">{selected.category} · {selected.platforms?.join(" · ")}</span><h2>{selected.name}</h2><p>{selected.description||"No description yet."}</p><p className="source">Repository · {selected.id.project}</p><button className="install" disabled={(()=>{const r=selected.latest?.[catalogChannel]||selected.latest?.stable||selected.latest?.beta||selected.latest?.development;const a=r?.artifacts?.find((z:any)=>["apk","apks","xapk","apkm"].includes(z.kind));const p=selected.packageIdentity||a?.packageIdentity;const i=p?installed[p]:undefined;return !!i&&Number(a?.versionCode??r?.version?.code??0)<=Number(i.versionCode??0)})()} onClick={()=>install(selected)}>{(()=>{const r=selected.latest?.[catalogChannel]||selected.latest?.stable||selected.latest?.beta||selected.latest?.development;const a=r?.artifacts?.find((z:any)=>["apk","apks","xapk","apkm"].includes(z.kind));const p=selected.packageIdentity||a?.packageIdentity;const i=p?installed[p]:undefined;return !a?"BUILD":!i?"INSTALL":Number(a?.versionCode??r?.version?.code??0)>Number(i.versionCode??0)?"UPDATE":"CURRENT"})()}</button></div></div><div className="detail-grid"><div><h3>Current channels</h3>{["stable","beta","development"].map((c:any)=>{const r=selected.latest?.[c];return <p key={c}>{c.toUpperCase()} · {r?r.version.name:"Not published"}</p>})}</div><div><h3>Details</h3><p>Package · {selected.packageIdentity||"Detected during build"}</p><p>Platforms · {selected.platforms?.join(", ")||"Android"}</p><p>Source · GitHub</p></div></div><section className="release-history"><h3>Version history</h3>{releaseHistory.length?releaseHistory.map((h:any)=><article className="card compact" key={h.release?.id||h.createdAt}><strong>{h.release?.version_name||h.release?.versionName||"Unknown version"}</strong><span>{h.reason} · {h.createdAt?new Date(h.createdAt).toLocaleString():""}</span><small>{h.release?.notes||"No release notes."}</small>{h.release?.artifacts?.length?<button className="choice" onClick={e=>{e.stopPropagation();installRelease(selected,h.release)}}>INSTALL THIS VERSION</button>:null}</article>):<p>No release history loaded.</p>}</section><section className="release-history"><h3>Build activity</h3>{builds.filter((b:any)=>b.repository===selected.id.project).length?builds.filter((b:any)=>b.repository===selected.id.project).slice(0,10).map((b:any)=><article className="card compact" key={b.id}><strong>{b.status.toUpperCase()}</strong><span>{b.ref} · {b.variant} · {b.channel}</span>{b.error&&<small>{b.error}</small>}</article>):<p>No build records for this repository.</p>}</section></section>}

  {tab==="Build"&&<section className="content build-panel"><div className="section-head"><div><span>BUILD FROM SOURCE</span><h2>GitHub → APK</h2></div><span>AUTOMATIC</span></div><p>Private repositories use the server-side GitHub access token. AEM discovers accessible repositories, watches for APK releases and can queue a build when no APK is published.</p><div className="build-form"><input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="owner/repository or GitHub URL"/><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Branch, tag or commit"/><select value={variant} onChange={e=>setVariant(e.target.value)}><option value="debug">Debug</option><option value="release">Release</option></select><select value={channel} onChange={e=>setChannel(e.target.value as any)}><option value="development">Development</option><option value="beta">Beta</option><option value="stable">Stable</option></select><button className="install" onClick={build} disabled={building||!repo.trim()}>{building?"QUEUEING…":"BUILD APK"}</button></div>{buildMessage&&<p className="build-message">{buildMessage}</p>}<div className="build-list"><h3>Build queue</h3>{builds.length?builds.map(b=><article className="card compact" key={b.id}><strong>{b.repository}</strong><span>{b.ref} · {b.variant} · {b.status}</span>{b.error&&<small>{b.error}</small>}</article>):<p>No builds yet.</p>}</div></section>}

  {tab==="Updates"&&<section className="content"><div className="section-head"><div><span>UPDATES</span><h2>Available releases</h2></div><span>{apps.filter(a=>a.latest?.stable||a.latest?.beta||a.latest?.development).length} tracked</span></div><div className="grid">{apps.filter(a=>a.latest?.stable||a.latest?.beta||a.latest?.development).map(a=><AppCard key={a.id.project} app={a} onOpen={()=>openApp(a)} onInstall={()=>install(a)} onOpenInstalled={(p)=>Capacitor.isNativePlatform()?AemInstaller.openInstalled({packageName:p}):window.open(a.sourceUrl,"_blank")} installed={(() => { const p=a.packageIdentity||a.latest?.stable?.artifacts?.find((x:any)=>x.packageIdentity)?.packageIdentity; return p?installed[p]:undefined; })()}/>)}</div></section>}

  {tab==="Downloads"&&<section className="content"><div className="section-head"><div><span>DOWNLOADS</span><h2>Download history</h2></div><span>{downloadUnit==="auto"?"AUTO":downloadUnit}</span></div>{downloads.length ? downloads.map((d:any) => <article className="card compact" key={d.id}><strong>{d.filename}</strong><span>{d.status}</span></article>) : <p>No downloads recorded yet.</p>}</section>
  {tab==="Admin"&&<section className="content"><div className="section-head"><div><span>OWNER CONSOLE</span><h2>AEM Admin</h2></div><span>OVERSIGHT</span></div><p>Search public GitHub repositories or enter private repositories directly in Build. Discovery runs automatically and does not require rebuilding the Store app.</p><div className="build-form"><input value={githubSearch} onChange={e=>setGithubSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchGithub()} placeholder="Search public GitHub repositories"/><button className="install" onClick={searchGithub} disabled={searchingGithub}>{searchingGithub?"SEARCHING…":"SEARCH GITHUB"}</button></div><div className="grid">{githubResults.map(r=><article className="card compact" key={r.full_name}><strong>{r.full_name}</strong><span>{r.language||"Unknown"} · ★ {r.stargazers_count||0}</span><p>{r.description||"No description."}</p><button className="install" onClick={()=>addGithub(r.full_name)}>ADD TO AEM</button></article>)}</div></section>}

  {tab==="Settings"&&<section className="content settings-page"><div className="section-head"><div><span>PREFERENCES</span><h2>Settings</h2></div><button className="install" onClick={load}>{syncing?"SYNCING…":"REFRESH CATALOG"}</button></div>
  <Setting title="Appearance" open={settingsOpen==="appearance"} onClick={()=>setSettingsOpen(settingsOpen==="appearance"?null:"appearance")}><div className="choice-row">{(["light","dark","system"] as const).map(v=><button className={appearance===v?"choice active-choice":"choice"} key={v} onClick={()=>saveAppearance(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div></Setting>
  <Setting title="Notifications" open={settingsOpen==="notifications"} onClick={()=>setSettingsOpen(settingsOpen==="notifications"?null:"notifications")}><p>Release and catalog notifications are {notificationsEnabled?"enabled":"disabled"}.</p><div className="choice-row"><button className={notificationsEnabled?"choice active-choice":"choice"} onClick={()=>saveToggle("aem-notifications",setNotificationsEnabled,!notificationsEnabled)}>{notificationsEnabled?"Disable notifications":"Enable notifications"}</button></div></Setting>
  <Setting title="Downloads" open={settingsOpen==="downloads"} onClick={()=>setSettingsOpen(settingsOpen==="downloads"?null:"downloads")}><p>Download records are stored in AEM. Choose the display unit used in download history and progress.</p><div className="choice-row">{(["auto","B","KB","MB","GB"] as const).map(v=><button key={v} className={downloadUnit===v?"choice active-choice":"choice"} onClick={()=>saveDownloadUnit(v)}>{v==="auto"?"Auto":v}</button>)}</div><div className="choice-row"><button className={wifiOnly?"choice active-choice":"choice"} onClick={()=>saveToggle("aem-wifi-only",setWifiOnly,!wifiOnly)}>{wifiOnly?"Wi-Fi only: ON":"Wi-Fi only: OFF"}</button></div></Setting>
  <Setting title="Installation" open={settingsOpen==="installer"} onClick={()=>setSettingsOpen(settingsOpen==="installer"?null:"installer")}><p>Use Android PackageInstaller directly, or AEM's split-package session for APK/APKS/XAPK/APKM archives.</p><div className="choice-row"><button className={installer==="system"?"choice active-choice":"choice"} onClick={()=>saveInstaller("system")}>Package Installer</button><button className={installer==="split"?"choice active-choice":"choice"} onClick={()=>saveInstaller("split")}>AEM Split Installer</button></div></Setting>
  <Setting title="Updates & sync" open={settingsOpen==="updates"} onClick={()=>setSettingsOpen(settingsOpen==="updates"?null:"updates")}><p>AEM refreshes its catalog on app focus and every five minutes while automatic refresh is enabled. GitHub discovery runs server-side.</p><div className="choice-row"><button className={autoSync?"choice active-choice":"choice"} onClick={()=>saveToggle("aem-auto-sync",setAutoSync,!autoSync)}>{autoSync?"Automatic refresh: ON":"Automatic refresh: OFF"}</button><button className="choice" onClick={load}>REFRESH NOW</button></div><p>Last GitHub sync: {syncState?.last_success_at?new Date(syncState.last_success_at).toLocaleString():"Not recorded"} · {syncState?.repositories_scanned??0} repositories · {syncState?.artifacts_discovered??0} artifacts.</p></Setting>
  <Setting title="Release channel" open={settingsOpen==="channels"} onClick={()=>setSettingsOpen(settingsOpen==="channels"?null:"channels")}><p>The selected channel is used first when choosing the release shown on app cards.</p><div className="choice-row">{(["stable","beta","development"] as const).map(v=><button className={catalogChannel===v?"choice active-choice":"choice"} key={v} onClick={()=>saveChannel(v)}>{v.toUpperCase()}</button>)}</div></Setting>
  <Setting title="Catalog / source" open={settingsOpen==="providers"} onClick={()=>setSettingsOpen(settingsOpen==="providers"?null:"providers")}><p>The catalog is source-provider driven. GitHub is currently the active provider; the provider registry is stored in Supabase so another provider can be added without rebuilding the Store.</p>{providers.map((p:any)=><div className="provider-row" key={p.id}><strong>{p.label}</strong><span>{p.active?"ACTIVE":"INACTIVE"} · {p.id}</span></div>)}</Setting>
  <Setting title="Storage" open={settingsOpen==="storage"} onClick={()=>setSettingsOpen(settingsOpen==="storage"?null:"storage")}><p>AEM-published APKs are stored in the AEM Supabase Storage bucket. The catalog receives durable artifact URLs.</p></Setting>
  <Setting title="Security & permissions" open={settingsOpen==="security"} onClick={()=>setSettingsOpen(settingsOpen==="security"?null:"security")}><p>GitHub credentials never enter the frontend. Native installation uses Android PackageInstaller and may require Android's install permission.</p>{Capacitor.isNativePlatform()&&<button className="choice" onClick={()=>AemInstaller.openInstallPermission()}>OPEN INSTALL PERMISSION</button>}</Setting>
  <Setting title="About" open={settingsOpen==="about"} onClick={()=>setSettingsOpen(settingsOpen==="about"?null:"about")}><p>AEM Store is a web-first Android software store. Applications are discovered from configured providers rather than hardcoded into the Store APK.</p></Setting>
 </section>}

<footer><span>● {connected?"Supabase connected":"Using local catalog"}</span><span>GitHub discovery · Android · Web</span></footer>
 </main>
}

function AppCard({app,onOpen,onInstall,onOpenInstalled,installed}:{app:any;onOpen:()=>void;onInstall:()=>void;onOpenInstalled:(packageName:string)=>void;installed?:{versionName:string;versionCode:number}}){const preferred=(localStorage.getItem("aem-channel")||"stable") as "stable"|"beta"|"development";const release=app.latest?.[preferred]||app.latest?.stable||app.latest?.beta||app.latest?.development;const artifact=release?.artifacts?.find((x:any)=>["apk","apks","xapk","apkm"].includes(x.kind));const packageName=app.packageIdentity||artifact?.packageIdentity||"";const availableCode=Number(artifact?.versionCode??release?.version?.code??0);const installedCode=Number(installed?.versionCode??0);const action=!artifact?"BUILD":!installed?"INSTALL":availableCode>installedCode?"UPDATE":"CURRENT";return <article className="card" onClick={onOpen}><div className="app-icon">{app.name[0]}</div><div className="card-main"><div className="meta">{app.category} · {app.platforms?.join(" · ")}</div><h3>{app.name}</h3><p>{app.description||"No description yet."}</p><div className="chips">{(app.functionality||[]).slice(0,3).map((x:string)=><span key={x}>{x}</span>)}</div><small>{release?`Latest ${release.version.name}${installed?` · Installed ${installed.versionName}`:""}`:"APK not published yet · repository tracked"}</small></div><button className="install" disabled={action==="CURRENT"} onClick={e=>{e.stopPropagation();if(action==="CURRENT"&&packageName){onOpenInstalled(packageName)}else{onInstall()}}}>{action}</button></article>}

function Setting({title,open,onClick,children}:{title:string;open:boolean;onClick:()=>void;children:any}){return <section className={open?"setting open":"setting"}><button className="setting-head" onClick={onClick}><strong>{title}</strong><span>{open?"−":"+"}</span></button>{open&&<div className="setting-body">{children}</div>}</section>}
