create table if not exists public.aem_signing_worker_auth (
  id bigint generated by default as identity primary key,
  token_sha256 text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.aem_signing_worker_auth enable row level security;
revoke all on table public.aem_signing_worker_auth from anon, authenticated;
