-- Squashed AEM catalog baseline. This file represents the final schema created by the
-- historical 20260921 migrations so the repository is a usable source of truth.

create extension if not exists pgcrypto;

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  provider text not null,
  project text not null,
  package_identity text,
  name text not null,
  description text,
  source_url text,
  icon_url text,
  platforms text[] not null default '{}',
  category text not null default 'Other',
  functionality text[] not null default '{}',
  screenshots text[] not null default '{}',
  permissions text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  rollback_release_id bigint,
  source_external_id text,
  source_visibility text
);

create unique index if not exists applications_provider_project_key on public.applications(provider,project);
create unique index if not exists applications_provider_external_id_key on public.applications(provider,source_external_id) where source_external_id is not null;

create table if not exists public.releases (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  source_release_id text not null,
  version_name text not null,
  version_code bigint,
  channel text not null default 'stable' check (channel in ('stable','beta','development')),
  status text not null default 'published' check (status in ('draft','published','withdrawn')),
  title text,
  notes text,
  published_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists releases_application_id_source_release_id_key on public.releases(application_id,source_release_id);
create index if not exists releases_application_idx on public.releases(application_id);

alter table public.applications add constraint applications_rollback_release_id_fkey foreign key (rollback_release_id) references public.releases(id) on delete set null;

create table if not exists public.artifacts (
  id bigint generated by default as identity primary key,
  release_id bigint not null references public.releases(id) on delete cascade,
  platform text not null,
  kind text not null,
  filename text not null,
  download_url text not null,
  size_bytes bigint,
  sha256 text,
  package_identity text,
  signing_certificate_sha256 text,
  version_code bigint
);
create index if not exists artifacts_release_idx on public.artifacts(release_id);

create table if not exists public.release_history (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  release_id bigint not null references public.releases(id) on delete cascade,
  reason text not null check (reason in ('published','withdrawn','rollback-target')),
  created_at timestamptz not null default now()
);
create index if not exists release_history_application_idx on public.release_history(application_id);
create index if not exists release_history_release_idx on public.release_history(release_id);
create index if not exists release_history_application_created_idx on public.release_history(application_id,created_at desc);

create table if not exists public.build_requests (
  id uuid primary key default gen_random_uuid(),
  repository text not null,
  ref text not null default 'main',
  source_kind text not null default 'github',
  module text,
  variant text default 'debug',
  channel text not null default 'development' check (channel in ('stable','beta','development')),
  status text not null default 'queued' check (status in ('queued','running','succeeded','failed','cancelled')),
  workflow_run_id bigint,
  application_id bigint references public.applications(id) on delete set null,
  release_id bigint references public.releases(id) on delete set null,
  artifact_id bigint references public.artifacts(id) on delete set null,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists build_requests_application_idx on public.build_requests(application_id);
create index if not exists build_requests_release_idx on public.build_requests(release_id);
create index if not exists build_requests_artifact_idx on public.build_requests(artifact_id);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  title text not null,
  body text not null,
  app_id bigint references public.applications(id) on delete set null,
  release_id bigint references public.releases(id) on delete set null,
  download_id uuid,
  read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_app_idx on public.notifications(app_id);
create index if not exists notifications_release_idx on public.notifications(release_id);
create index if not exists notifications_created_idx on public.notifications(created_at desc);

create table if not exists public.downloads (
  id uuid primary key default gen_random_uuid(),
  application_id bigint references public.applications(id) on delete set null,
  release_id bigint references public.releases(id) on delete set null,
  filename text not null,
  url text not null,
  status text not null default 'queued',
  bytes_downloaded bigint not null default 0,
  total_bytes bigint,
  error text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  client_id text
);
create index if not exists downloads_application_idx on public.downloads(application_id);
create index if not exists downloads_release_idx on public.downloads(release_id);
create index if not exists downloads_created_idx on public.downloads(created_at desc);
create index if not exists downloads_client_idx on public.downloads(client_id,created_at desc);

create table if not exists public.source_providers (
  id text primary key,
  label text not null,
  active boolean not null default false,
  config jsonb not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.source_sync_state (
  provider text primary key references public.source_providers(id) on delete cascade,
  status text not null default 'never',
  last_started_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  repositories_scanned integer not null default 0,
  applications_discovered integer not null default 0,
  releases_discovered integer not null default 0,
  artifacts_discovered integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.source_providers(id,label,active,config)
values ('github','GitHub',true,'{}')
on conflict(id) do update set label=excluded.label,active=excluded.active,config=excluded.config,updated_at=now();
insert into public.source_sync_state(provider) values('github') on conflict(provider) do nothing;

alter table public.applications enable row level security;
alter table public.releases enable row level security;
alter table public.artifacts enable row level security;
alter table public.release_history enable row level security;
alter table public.build_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.downloads enable row level security;
alter table public.source_providers enable row level security;
alter table public.source_sync_state enable row level security;

create policy "public read applications" on public.applications for select to anon,authenticated using(true);
create policy "public read releases" on public.releases for select to anon,authenticated using(true);
create policy "public read published artifacts" on public.artifacts for select to anon,authenticated using(exists(select 1 from public.releases r where r.id=release_id and r.status='published'));
create policy "public read release history" on public.release_history for select to anon,authenticated using(true);
create policy "build requests public insert" on public.build_requests for insert to anon,authenticated with check(true);
create policy "build requests public read" on public.build_requests for select to anon,authenticated using(true);
create policy "build requests public update" on public.build_requests for update to anon,authenticated using(true) with check(status in ('queued','running','succeeded','failed','cancelled'));
create policy "notifications public read" on public.notifications for select to anon,authenticated using(true);
create policy "downloads client insert" on public.downloads for insert to anon,authenticated with check(client_id is not null and client_id=current_setting('request.headers',true)::json->>'x-aem-client-id');
create policy "downloads client update" on public.downloads for update to anon,authenticated using(client_id=current_setting('request.headers',true)::json->>'x-aem-client-id') with check(client_id=current_setting('request.headers',true)::json->>'x-aem-client-id');
create policy "downloads client read" on public.downloads for select to anon,authenticated using(client_id=current_setting('request.headers',true)::json->>'x-aem-client-id');
create policy "public read source providers" on public.source_providers for select to anon,authenticated using(true);
create policy "public read source sync state" on public.source_sync_state for select to anon,authenticated using(true);

grant select on public.applications,public.releases,public.artifacts,public.release_history,public.source_providers,public.source_sync_state to anon,authenticated;
grant insert,select on public.build_requests to anon,authenticated;
grant insert,select,update on public.downloads to anon,authenticated;

create or replace function public.aem_release_event_ingest()
returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
  if tg_op='INSERT' then
    insert into public.release_history(application_id,release_id,reason) values(new.application_id,new.id,'published');
    insert into public.notifications(kind,title,body,app_id,release_id) values('release','New release',coalesce(new.title,new.version_name)||' is now available.',new.application_id,new.id);
  elsif tg_op='UPDATE' and old.status is distinct from new.status then
    if new.status='published' then
      insert into public.release_history(application_id,release_id,reason) values(new.application_id,new.id,'published');
      insert into public.notifications(kind,title,body,app_id,release_id) values('release','Release published',coalesce(new.title,new.version_name)||' is now available.',new.application_id,new.id);
    elsif new.status='withdrawn' then
      insert into public.release_history(application_id,release_id,reason) values(new.application_id,new.id,'withdrawn');
      insert into public.notifications(kind,title,body,app_id,release_id) values('security','Release withdrawn',coalesce(new.title,new.version_name)||' was withdrawn.',new.application_id,new.id);
    end if;
  end if;
  return new;
end $$;
revoke execute on function public.aem_release_event_ingest() from public,anon,authenticated;

drop trigger if exists aem_release_event_ingest on public.releases;
create trigger aem_release_event_ingest after insert or update on public.releases for each row execute function public.aem_release_event_ingest();
